In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [29]:
sent=['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good'
]

In [30]:
## define vocabulaire size
voc_size=10000

In [ ]:
## one hot representation
one_hot_representation=[one_hot(words,voc_size) for words in sent]
one_hot_representation

[[6016, 9281, 8211, 9120],
 [6016, 9281, 8211, 3948],
 [6016, 8744, 8211, 4648],
 [3818, 4266, 9407, 4368, 8036],
 [3818, 4266, 9407, 4368, 293],
 [6754, 6016, 3630, 8211, 9950],
 [726, 4382, 4884, 4368]]

In [32]:
## word Embeding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [33]:
import numpy as np

In [34]:
sent_length=8
embedding_docs=pad_sequences(one_hot_representation,padding='pre',maxlen=sent_length)

In [35]:
print(embedding_docs)

[[   0    0    0    0 6016 9281 8211 9120]
 [   0    0    0    0 6016 9281 8211 3948]
 [   0    0    0    0 6016 8744 8211 4648]
 [   0    0    0 3818 4266 9407 4368 8036]
 [   0    0    0 3818 4266 9407 4368  293]
 [   0    0    0 6754 6016 3630 8211 9950]
 [   0    0    0    0  726 4382 4884 4368]]


In [36]:
dim=10

In [49]:
## feature-representation
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [52]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[[-2.2403205e-02,  4.0653337e-02, -4.3747760e-02,  2.5088739e-02,
          1.9442294e-02, -2.4247432e-02,  2.6502792e-02, -2.7546771e-03,
         -1.8301141e-02, -3.0814672e-02],
        [-2.2403205e-02,  4.0653337e-02, -4.3747760e-02,  2.5088739e-02,
          1.9442294e-02, -2.4247432e-02,  2.6502792e-02, -2.7546771e-03,
         -1.8301141e-02, -3.0814672e-02],
        [-2.2403205e-02,  4.0653337e-02, -4.3747760e-02,  2.5088739e-02,
          1.9442294e-02, -2.4247432e-02,  2.6502792e-02, -2.7546771e-03,
         -1.8301141e-02, -3.0814672e-02],
        [-2.2403205e-02,  4.0653337e-02, -4.3747760e-02,  2.5088739e-02,
          1.9442294e-02, -2.4247432e-02,  2.6502792e-02, -2.7546771e-03,
         -1.8301141e-02, -3.0814672e-02],
        [-4.1619100e-02, -1.3216842e-02, -3.9762475e-02, -1.9807864e-02,
          3.6074016e-02, -1.6160894e-02,  3.7471864e-02,  3.3876631e-02,
         -2.9616570e-02,  1.2608077e-02],
        [ 1.5343141e-02, -2.6647938e-02, -1.7721545e-02, -3.